// Copyright 2026 Tamás Gulácsi. All rights reserved.
//
// SPDX-License-Identifier: AGPL-3.0

package enums

import (
	"bytes"
	"encoding/xml"
	"errors"
	"fmt"
	"io"
	"log"
	"maps"
	"os"
	"slices"

	"golang.org/x/text/encoding/htmlindex"
)

type Enums map[string]map[string]string

func WriteGeneratedFile(fileName, packageName, mapName string, enums Enums) error {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, `// Generated by github.com/UNO-SOFT/boma/enums/enums-from-xsd. DO NOT EDIT

package %s

var %s = map[string]map[string]string{
`,
		packageName, mapName,
	)
	for _, typeName := range slices.Sorted(maps.Keys(enums)) {
		fmt.Fprintf(&buf, "\t%q: {\n", typeName)
		for _, k := range slices.Sorted(maps.Keys(enums[typeName])) {
			fmt.Fprintf(&buf, "\t\t%q: %q,\n", k, enums[typeName][k])
		}
		buf.WriteString("\t},")
	}
	buf.WriteString("}\n")
	if fileName == "" || fileName == "-" {
		_, err := os.Stdout.Write(buf.Bytes())
		return err
	}
	return os.WriteFile(fileName, buf.Bytes(), 0664)
}

func ParseFiles(fileName ...string) (Enums, error) {
	if len(fileName) == 0 {
		fileName = append(fileName, "-")
	}
	enums := make(Enums, 1+len(fileName))
	for _, fn := range fileName {
		r := os.Stdin
		if !(fn == "" || fn == "-") {
			var err error
			if r, err = os.Open(fn); err != nil {
				return enums, err
			}
		}
		err := Parse(enums, r)
		r.Close()
		if err != nil {
			return enums, err
		}
	}
	return enums, nil
}

func Parse(m Enums, r io.Reader) error {
	dec := xml.NewDecoder(r)
	dec.CharsetReader = func(charset string, input io.Reader) (io.Reader, error) {
		enc, err := htmlindex.Get(charset)
		if err != nil {
			return input, err
		}
		return enc.NewDecoder().Reader(input), nil
	}

	var path []string
	var typeName, value string
	var documentation bool
	for {
		tok, err := dec.Token()
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return err
		}
		// simpleType > ... > enumeration > annotation > documentation
		switch x := tok.(type) {
		case xml.StartElement:
			documentation = false
			nm := x.Name.Local
			switch nm {
			case "simpleType":
				for _, a := range x.Attr {
					if a.Name.Local == "name" {
						typeName = a.Value
						break
					}
				}
			case "enumeration":
				for _, a := range x.Attr {
					if a.Name.Local == "value" {
						value = a.Value
						break
					}
				}
			case "annotation":
			case "documentation":
				documentation = true
			}
			path = append(path, nm)
		case xml.EndElement:
			path = path[:len(path)-1]
		case xml.CharData:
			if documentation && typeName != "" && value != "" {
				b := bytes.TrimSpace(x)
				if len(b) != 0 {
					if m[typeName] == nil {
						m[typeName] = make(map[string]string)
					}
					m[typeName][value] = string(b)
				}
			}
		case xml.ProcInst:
		case xml.Comment:
		default:
			typeName, value = "", ""
			log.Printf("%T %#v", tok, tok)
		}
	}

	return nil
}
