// Generated by gen_xml_test.sh. DO NOT EDIT

package boma

import (
	"bytes"
	"encoding/xml"
	"errors"
	"io"
	"testing"

	"github.com/valyala/bytebufferpool"
	"github.com/valyala/quicktemplate"
)

func checkXML(t *testing.T, I interface{ StreamXML(*quicktemplate.Writer) }) {
	B := bytebufferpool.Get()
	defer bytebufferpool.Put(B)
	W := quicktemplate.AcquireWriter(B)
	I.StreamXML(W)
	quicktemplate.ReleaseWriter(W)
	t.Log(string(B.Bytes()))
	dec := xml.NewDecoder(bytes.NewReader(B.Bytes()))
	for {
		_, err := dec.Token()
		if err != nil {
			if !errors.Is(err, io.EOF) {
				t.Error(err)
			}
			break
		}
	}
}
func TestXextractXmlBomaMsgRequestStreamXML(t *testing.T) { checkXML(t, (&extractXmlBomaMsgRequest{})) }
