// Code generated by qtc from "xmls.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line xmls.qtpl:1
package soap

//line xmls.qtpl:3
import "encoding/base64"

//line xmls.qtpl:4
import "encoding/xml"

//line xmls.qtpl:5
import "fmt"

//line xmls.qtpl:6
import "github.com/tgulacsi/go/bufpool"

//line xmls.qtpl:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line xmls.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line xmls.qtpl:10
func (x extractXmlBomaMsgRequest) StreamXML(qw422016 *qt422016.Writer) {
//line xmls.qtpl:10
	qw422016.N().S(` <extractXmlBomaMsgRequest xmlns="http://www.qualysoft.hu/services/schemas/boma/bomamsgservices" xmlns:basebns="http://www.mabisz.hu/boma"> <msgTypeName>`)
//line xmls.qtpl:12
	qw422016.N().S(x.Type)
//line xmls.qtpl:12
	qw422016.N().S(`</msgTypeName> <serviceRequested>`)
//line xmls.qtpl:13
	qw422016.N().S(x.Service)
//line xmls.qtpl:13
	qw422016.N().S(`</serviceRequested> <encryptedKey>`)
//line xmls.qtpl:14
	StreamXML(qw422016, x.Key)
//line xmls.qtpl:14
	qw422016.N().S(`</encryptedKey> <msgData>`)
//line xmls.qtpl:15
	StreamXML(qw422016, x.Data)
//line xmls.qtpl:15
	qw422016.N().S(`</msgData> </extractXmlBomaMsgRequest> `)
//line xmls.qtpl:17
}

//line xmls.qtpl:17
func (x extractXmlBomaMsgRequest) WriteXML(qq422016 qtio422016.Writer) {
//line xmls.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line xmls.qtpl:17
	x.StreamXML(qw422016)
//line xmls.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line xmls.qtpl:17
}

//line xmls.qtpl:17
func (x extractXmlBomaMsgRequest) XML() string {
//line xmls.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line xmls.qtpl:17
	x.WriteXML(qb422016)
//line xmls.qtpl:17
	qs422016 := string(qb422016.B)
//line xmls.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line xmls.qtpl:17
	return qs422016
//line xmls.qtpl:17
}

//line xmls.qtpl:19
func StreamXML(qw422016 *qt422016.Writer, s any) {
//line xmls.qtpl:19
	qw422016.N().S(` `)
//line xmls.qtpl:21
	xmlEsc := func(x string) string {
		buf := bufpool.Get()
		defer bufpool.Put(buf)
		if err := xml.EscapeText(buf, []byte(x)); err != nil {
			panic(fmt.Errorf("escape %q: %w", x, err))
		}
		return buf.String()
	}

//line xmls.qtpl:29
	qw422016.N().S(` `)
//line xmls.qtpl:30
	switch x := s.(type) {
//line xmls.qtpl:31
	case []byte:
//line xmls.qtpl:31
		qw422016.N().S(base64.StdEncoding.EncodeToString(x))
//line xmls.qtpl:31
		qw422016.N().S(` `)
//line xmls.qtpl:32
	case string:
//line xmls.qtpl:32
		qw422016.N().S(xmlEsc(x))
//line xmls.qtpl:32
		qw422016.N().S(` `)
//line xmls.qtpl:33
	default:
//line xmls.qtpl:33
		panic(fmt.Errorf("unknown type %T", s))

//line xmls.qtpl:33
		qw422016.N().S(` `)
//line xmls.qtpl:34
	}
//line xmls.qtpl:34
	qw422016.N().S(` `)
//line xmls.qtpl:35
}

//line xmls.qtpl:35
func WriteXML(qq422016 qtio422016.Writer, s any) {
//line xmls.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line xmls.qtpl:35
	StreamXML(qw422016, s)
//line xmls.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line xmls.qtpl:35
}

//line xmls.qtpl:35
func XML(s any) string {
//line xmls.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line xmls.qtpl:35
	WriteXML(qb422016, s)
//line xmls.qtpl:35
	qs422016 := string(qb422016.B)
//line xmls.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line xmls.qtpl:35
	return qs422016
//line xmls.qtpl:35
}
